//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace MISUI.ServiceFrameworkMgmt {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="FrameworkManagementServiceSoap", Namespace="http://tempuri.org/")]
    public partial class FrameworkManagementService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private AuthSoapHd authSoapHdValueField;
        
        private System.Threading.SendOrPostCallback AddEditFrameworkOperationCompleted;
        
        private System.Threading.SendOrPostCallback PopulateFrameworkDetailsOperationCompleted;
        
        private System.Threading.SendOrPostCallback PopulateAllFrameworksOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public FrameworkManagementService() {
            this.Url = global::MISUI.Properties.Settings.Default.MISUI_ServiceFrameworkMgmt_FrameworkManagementService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public AuthSoapHd AuthSoapHdValue {
            get {
                return this.authSoapHdValueField;
            }
            set {
                this.authSoapHdValueField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event AddEditFrameworkCompletedEventHandler AddEditFrameworkCompleted;
        
        /// <remarks/>
        public event PopulateFrameworkDetailsCompletedEventHandler PopulateFrameworkDetailsCompleted;
        
        /// <remarks/>
        public event PopulateAllFrameworksCompletedEventHandler PopulateAllFrameworksCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthSoapHdValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AddEditFramework", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int AddEditFramework(FrameworkBO objFrameworkBO) {
            object[] results = this.Invoke("AddEditFramework", new object[] {
                        objFrameworkBO});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void AddEditFrameworkAsync(FrameworkBO objFrameworkBO) {
            this.AddEditFrameworkAsync(objFrameworkBO, null);
        }
        
        /// <remarks/>
        public void AddEditFrameworkAsync(FrameworkBO objFrameworkBO, object userState) {
            if ((this.AddEditFrameworkOperationCompleted == null)) {
                this.AddEditFrameworkOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddEditFrameworkOperationCompleted);
            }
            this.InvokeAsync("AddEditFramework", new object[] {
                        objFrameworkBO}, this.AddEditFrameworkOperationCompleted, userState);
        }
        
        private void OnAddEditFrameworkOperationCompleted(object arg) {
            if ((this.AddEditFrameworkCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddEditFrameworkCompleted(this, new AddEditFrameworkCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthSoapHdValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PopulateFrameworkDetails", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable PopulateFrameworkDetails(FrameworkBO objFrameworkBO) {
            object[] results = this.Invoke("PopulateFrameworkDetails", new object[] {
                        objFrameworkBO});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void PopulateFrameworkDetailsAsync(FrameworkBO objFrameworkBO) {
            this.PopulateFrameworkDetailsAsync(objFrameworkBO, null);
        }
        
        /// <remarks/>
        public void PopulateFrameworkDetailsAsync(FrameworkBO objFrameworkBO, object userState) {
            if ((this.PopulateFrameworkDetailsOperationCompleted == null)) {
                this.PopulateFrameworkDetailsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPopulateFrameworkDetailsOperationCompleted);
            }
            this.InvokeAsync("PopulateFrameworkDetails", new object[] {
                        objFrameworkBO}, this.PopulateFrameworkDetailsOperationCompleted, userState);
        }
        
        private void OnPopulateFrameworkDetailsOperationCompleted(object arg) {
            if ((this.PopulateFrameworkDetailsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PopulateFrameworkDetailsCompleted(this, new PopulateFrameworkDetailsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthSoapHdValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PopulateAllFrameworks", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable PopulateAllFrameworks() {
            object[] results = this.Invoke("PopulateAllFrameworks", new object[0]);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void PopulateAllFrameworksAsync() {
            this.PopulateAllFrameworksAsync(null);
        }
        
        /// <remarks/>
        public void PopulateAllFrameworksAsync(object userState) {
            if ((this.PopulateAllFrameworksOperationCompleted == null)) {
                this.PopulateAllFrameworksOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPopulateAllFrameworksOperationCompleted);
            }
            this.InvokeAsync("PopulateAllFrameworks", new object[0], this.PopulateAllFrameworksOperationCompleted, userState);
        }
        
        private void OnPopulateAllFrameworksOperationCompleted(object arg) {
            if ((this.PopulateAllFrameworksCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PopulateAllFrameworksCompleted(this, new PopulateAllFrameworksCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/", IsNullable=false)]
    public partial class AuthSoapHd : System.Web.Services.Protocols.SoapHeader {
        
        private string strUserNameField;
        
        private string strPasswordField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        public string strUserName {
            get {
                return this.strUserNameField;
            }
            set {
                this.strUserNameField = value;
            }
        }
        
        /// <remarks/>
        public string strPassword {
            get {
                return this.strPasswordField;
            }
            set {
                this.strPasswordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class FrameworkBO {
        
        private int frameworkIdField;
        
        private string frameworkEngNameField;
        
        private string frameworkNepNameField;
        
        private int baseYearIdField;
        
        private int firstYearIdField;
        
        private int secondYearIdField;
        
        private int thirdYearIdField;
        
        private string modeField;
        
        private decimal isEnableField;
        
        private decimal isLockedField;
        
        private string langField;
        
        /// <remarks/>
        public int FrameworkId {
            get {
                return this.frameworkIdField;
            }
            set {
                this.frameworkIdField = value;
            }
        }
        
        /// <remarks/>
        public string FrameworkEngName {
            get {
                return this.frameworkEngNameField;
            }
            set {
                this.frameworkEngNameField = value;
            }
        }
        
        /// <remarks/>
        public string FrameworkNepName {
            get {
                return this.frameworkNepNameField;
            }
            set {
                this.frameworkNepNameField = value;
            }
        }
        
        /// <remarks/>
        public int BaseYearId {
            get {
                return this.baseYearIdField;
            }
            set {
                this.baseYearIdField = value;
            }
        }
        
        /// <remarks/>
        public int FirstYearId {
            get {
                return this.firstYearIdField;
            }
            set {
                this.firstYearIdField = value;
            }
        }
        
        /// <remarks/>
        public int SecondYearId {
            get {
                return this.secondYearIdField;
            }
            set {
                this.secondYearIdField = value;
            }
        }
        
        /// <remarks/>
        public int ThirdYearId {
            get {
                return this.thirdYearIdField;
            }
            set {
                this.thirdYearIdField = value;
            }
        }
        
        /// <remarks/>
        public string Mode {
            get {
                return this.modeField;
            }
            set {
                this.modeField = value;
            }
        }
        
        /// <remarks/>
        public decimal IsEnable {
            get {
                return this.isEnableField;
            }
            set {
                this.isEnableField = value;
            }
        }
        
        /// <remarks/>
        public decimal IsLocked {
            get {
                return this.isLockedField;
            }
            set {
                this.isLockedField = value;
            }
        }
        
        /// <remarks/>
        public string Lang {
            get {
                return this.langField;
            }
            set {
                this.langField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void AddEditFrameworkCompletedEventHandler(object sender, AddEditFrameworkCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddEditFrameworkCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddEditFrameworkCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void PopulateFrameworkDetailsCompletedEventHandler(object sender, PopulateFrameworkDetailsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PopulateFrameworkDetailsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PopulateFrameworkDetailsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void PopulateAllFrameworksCompletedEventHandler(object sender, PopulateAllFrameworksCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PopulateAllFrameworksCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PopulateAllFrameworksCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591