//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace MISUI.ServiceVdcMun {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="VdcMunServiceSoap", Namespace="http://tempuri.org/")]
    public partial class VdcMunService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private AuthSoapHd authSoapHdValueField;
        
        private System.Threading.SendOrPostCallback HelloWorldOperationCompleted;
        
        private System.Threading.SendOrPostCallback InsertVdcMunOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteVdcMunByIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback SearchVdcMunByDistrictOperationCompleted;
        
        private System.Threading.SendOrPostCallback FetchMunVdcDetailsByIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateVdcMunByIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback FetchAllVdcMunOperationCompleted;
        
        private System.Threading.SendOrPostCallback populateVdcMunOperationCompleted;
        
        private System.Threading.SendOrPostCallback LockVdcMunOperationCompleted;
        
        private System.Threading.SendOrPostCallback UnlockVdcMunOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public VdcMunService() {
            this.Url = global::MISUI.Properties.Settings.Default.MISUI_ServiceVdcMun_VdcMunService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public AuthSoapHd AuthSoapHdValue {
            get {
                return this.authSoapHdValueField;
            }
            set {
                this.authSoapHdValueField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event HelloWorldCompletedEventHandler HelloWorldCompleted;
        
        /// <remarks/>
        public event InsertVdcMunCompletedEventHandler InsertVdcMunCompleted;
        
        /// <remarks/>
        public event DeleteVdcMunByIdCompletedEventHandler DeleteVdcMunByIdCompleted;
        
        /// <remarks/>
        public event SearchVdcMunByDistrictCompletedEventHandler SearchVdcMunByDistrictCompleted;
        
        /// <remarks/>
        public event FetchMunVdcDetailsByIdCompletedEventHandler FetchMunVdcDetailsByIdCompleted;
        
        /// <remarks/>
        public event UpdateVdcMunByIdCompletedEventHandler UpdateVdcMunByIdCompleted;
        
        /// <remarks/>
        public event FetchAllVdcMunCompletedEventHandler FetchAllVdcMunCompleted;
        
        /// <remarks/>
        public event populateVdcMunCompletedEventHandler populateVdcMunCompleted;
        
        /// <remarks/>
        public event LockVdcMunCompletedEventHandler LockVdcMunCompleted;
        
        /// <remarks/>
        public event UnlockVdcMunCompletedEventHandler UnlockVdcMunCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthSoapHdValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HelloWorld", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HelloWorld() {
            object[] results = this.Invoke("HelloWorld", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HelloWorldAsync() {
            this.HelloWorldAsync(null);
        }
        
        /// <remarks/>
        public void HelloWorldAsync(object userState) {
            if ((this.HelloWorldOperationCompleted == null)) {
                this.HelloWorldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHelloWorldOperationCompleted);
            }
            this.InvokeAsync("HelloWorld", new object[0], this.HelloWorldOperationCompleted, userState);
        }
        
        private void OnHelloWorldOperationCompleted(object arg) {
            if ((this.HelloWorldCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthSoapHdValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/InsertVdcMun", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int InsertVdcMun(VdcMun obj) {
            object[] results = this.Invoke("InsertVdcMun", new object[] {
                        obj});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void InsertVdcMunAsync(VdcMun obj) {
            this.InsertVdcMunAsync(obj, null);
        }
        
        /// <remarks/>
        public void InsertVdcMunAsync(VdcMun obj, object userState) {
            if ((this.InsertVdcMunOperationCompleted == null)) {
                this.InsertVdcMunOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsertVdcMunOperationCompleted);
            }
            this.InvokeAsync("InsertVdcMun", new object[] {
                        obj}, this.InsertVdcMunOperationCompleted, userState);
        }
        
        private void OnInsertVdcMunOperationCompleted(object arg) {
            if ((this.InsertVdcMunCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InsertVdcMunCompleted(this, new InsertVdcMunCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthSoapHdValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DeleteVdcMunById", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int DeleteVdcMunById(int id) {
            object[] results = this.Invoke("DeleteVdcMunById", new object[] {
                        id});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void DeleteVdcMunByIdAsync(int id) {
            this.DeleteVdcMunByIdAsync(id, null);
        }
        
        /// <remarks/>
        public void DeleteVdcMunByIdAsync(int id, object userState) {
            if ((this.DeleteVdcMunByIdOperationCompleted == null)) {
                this.DeleteVdcMunByIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteVdcMunByIdOperationCompleted);
            }
            this.InvokeAsync("DeleteVdcMunById", new object[] {
                        id}, this.DeleteVdcMunByIdOperationCompleted, userState);
        }
        
        private void OnDeleteVdcMunByIdOperationCompleted(object arg) {
            if ((this.DeleteVdcMunByIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteVdcMunByIdCompleted(this, new DeleteVdcMunByIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthSoapHdValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SearchVdcMunByDistrict", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable SearchVdcMunByDistrict(Users uBo) {
            object[] results = this.Invoke("SearchVdcMunByDistrict", new object[] {
                        uBo});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void SearchVdcMunByDistrictAsync(Users uBo) {
            this.SearchVdcMunByDistrictAsync(uBo, null);
        }
        
        /// <remarks/>
        public void SearchVdcMunByDistrictAsync(Users uBo, object userState) {
            if ((this.SearchVdcMunByDistrictOperationCompleted == null)) {
                this.SearchVdcMunByDistrictOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSearchVdcMunByDistrictOperationCompleted);
            }
            this.InvokeAsync("SearchVdcMunByDistrict", new object[] {
                        uBo}, this.SearchVdcMunByDistrictOperationCompleted, userState);
        }
        
        private void OnSearchVdcMunByDistrictOperationCompleted(object arg) {
            if ((this.SearchVdcMunByDistrictCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SearchVdcMunByDistrictCompleted(this, new SearchVdcMunByDistrictCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthSoapHdValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/FetchMunVdcDetailsById", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable FetchMunVdcDetailsById(string id) {
            object[] results = this.Invoke("FetchMunVdcDetailsById", new object[] {
                        id});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void FetchMunVdcDetailsByIdAsync(string id) {
            this.FetchMunVdcDetailsByIdAsync(id, null);
        }
        
        /// <remarks/>
        public void FetchMunVdcDetailsByIdAsync(string id, object userState) {
            if ((this.FetchMunVdcDetailsByIdOperationCompleted == null)) {
                this.FetchMunVdcDetailsByIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFetchMunVdcDetailsByIdOperationCompleted);
            }
            this.InvokeAsync("FetchMunVdcDetailsById", new object[] {
                        id}, this.FetchMunVdcDetailsByIdOperationCompleted, userState);
        }
        
        private void OnFetchMunVdcDetailsByIdOperationCompleted(object arg) {
            if ((this.FetchMunVdcDetailsByIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FetchMunVdcDetailsByIdCompleted(this, new FetchMunVdcDetailsByIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthSoapHdValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateVdcMunById", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int UpdateVdcMunById(VdcMun obj) {
            object[] results = this.Invoke("UpdateVdcMunById", new object[] {
                        obj});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateVdcMunByIdAsync(VdcMun obj) {
            this.UpdateVdcMunByIdAsync(obj, null);
        }
        
        /// <remarks/>
        public void UpdateVdcMunByIdAsync(VdcMun obj, object userState) {
            if ((this.UpdateVdcMunByIdOperationCompleted == null)) {
                this.UpdateVdcMunByIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateVdcMunByIdOperationCompleted);
            }
            this.InvokeAsync("UpdateVdcMunById", new object[] {
                        obj}, this.UpdateVdcMunByIdOperationCompleted, userState);
        }
        
        private void OnUpdateVdcMunByIdOperationCompleted(object arg) {
            if ((this.UpdateVdcMunByIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateVdcMunByIdCompleted(this, new UpdateVdcMunByIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthSoapHdValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/FetchAllVdcMun", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable FetchAllVdcMun(string lang) {
            object[] results = this.Invoke("FetchAllVdcMun", new object[] {
                        lang});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void FetchAllVdcMunAsync(string lang) {
            this.FetchAllVdcMunAsync(lang, null);
        }
        
        /// <remarks/>
        public void FetchAllVdcMunAsync(string lang, object userState) {
            if ((this.FetchAllVdcMunOperationCompleted == null)) {
                this.FetchAllVdcMunOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFetchAllVdcMunOperationCompleted);
            }
            this.InvokeAsync("FetchAllVdcMun", new object[] {
                        lang}, this.FetchAllVdcMunOperationCompleted, userState);
        }
        
        private void OnFetchAllVdcMunOperationCompleted(object arg) {
            if ((this.FetchAllVdcMunCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FetchAllVdcMunCompleted(this, new FetchAllVdcMunCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthSoapHdValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/populateVdcMun", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable populateVdcMun(int disId) {
            object[] results = this.Invoke("populateVdcMun", new object[] {
                        disId});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void populateVdcMunAsync(int disId) {
            this.populateVdcMunAsync(disId, null);
        }
        
        /// <remarks/>
        public void populateVdcMunAsync(int disId, object userState) {
            if ((this.populateVdcMunOperationCompleted == null)) {
                this.populateVdcMunOperationCompleted = new System.Threading.SendOrPostCallback(this.OnpopulateVdcMunOperationCompleted);
            }
            this.InvokeAsync("populateVdcMun", new object[] {
                        disId}, this.populateVdcMunOperationCompleted, userState);
        }
        
        private void OnpopulateVdcMunOperationCompleted(object arg) {
            if ((this.populateVdcMunCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.populateVdcMunCompleted(this, new populateVdcMunCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthSoapHdValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LockVdcMun", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int LockVdcMun(int vdcMunId) {
            object[] results = this.Invoke("LockVdcMun", new object[] {
                        vdcMunId});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void LockVdcMunAsync(int vdcMunId) {
            this.LockVdcMunAsync(vdcMunId, null);
        }
        
        /// <remarks/>
        public void LockVdcMunAsync(int vdcMunId, object userState) {
            if ((this.LockVdcMunOperationCompleted == null)) {
                this.LockVdcMunOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLockVdcMunOperationCompleted);
            }
            this.InvokeAsync("LockVdcMun", new object[] {
                        vdcMunId}, this.LockVdcMunOperationCompleted, userState);
        }
        
        private void OnLockVdcMunOperationCompleted(object arg) {
            if ((this.LockVdcMunCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LockVdcMunCompleted(this, new LockVdcMunCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthSoapHdValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UnlockVdcMun", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int UnlockVdcMun(int vdcMunId) {
            object[] results = this.Invoke("UnlockVdcMun", new object[] {
                        vdcMunId});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void UnlockVdcMunAsync(int vdcMunId) {
            this.UnlockVdcMunAsync(vdcMunId, null);
        }
        
        /// <remarks/>
        public void UnlockVdcMunAsync(int vdcMunId, object userState) {
            if ((this.UnlockVdcMunOperationCompleted == null)) {
                this.UnlockVdcMunOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUnlockVdcMunOperationCompleted);
            }
            this.InvokeAsync("UnlockVdcMun", new object[] {
                        vdcMunId}, this.UnlockVdcMunOperationCompleted, userState);
        }
        
        private void OnUnlockVdcMunOperationCompleted(object arg) {
            if ((this.UnlockVdcMunCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UnlockVdcMunCompleted(this, new UnlockVdcMunCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/", IsNullable=false)]
    public partial class AuthSoapHd : System.Web.Services.Protocols.SoapHeader {
        
        private string strUserNameField;
        
        private string strPasswordField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        public string strUserName {
            get {
                return this.strUserNameField;
            }
            set {
                this.strUserNameField = value;
            }
        }
        
        /// <remarks/>
        public string strPassword {
            get {
                return this.strPasswordField;
            }
            set {
                this.strPasswordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Users {
        
        private string usernameField;
        
        private string nameEngField;
        
        private string nameNepField;
        
        private string passwordField;
        
        private int officeField;
        
        private string roleField;
        
        private int userTypeField;
        
        private string mobileField;
        
        private string emailField;
        
        private string organizarionField;
        
        private int enableDisableField;
        
        private string requestStatusField;
        
        private int requestedByField;
        
        private int userIdField;
        
        private string districtField;
        
        private int isLockedField;
        
        /// <remarks/>
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        public string NameEng {
            get {
                return this.nameEngField;
            }
            set {
                this.nameEngField = value;
            }
        }
        
        /// <remarks/>
        public string NameNep {
            get {
                return this.nameNepField;
            }
            set {
                this.nameNepField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        public int Office {
            get {
                return this.officeField;
            }
            set {
                this.officeField = value;
            }
        }
        
        /// <remarks/>
        public string Role {
            get {
                return this.roleField;
            }
            set {
                this.roleField = value;
            }
        }
        
        /// <remarks/>
        public int UserType {
            get {
                return this.userTypeField;
            }
            set {
                this.userTypeField = value;
            }
        }
        
        /// <remarks/>
        public string Mobile {
            get {
                return this.mobileField;
            }
            set {
                this.mobileField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public string Organizarion {
            get {
                return this.organizarionField;
            }
            set {
                this.organizarionField = value;
            }
        }
        
        /// <remarks/>
        public int EnableDisable {
            get {
                return this.enableDisableField;
            }
            set {
                this.enableDisableField = value;
            }
        }
        
        /// <remarks/>
        public string RequestStatus {
            get {
                return this.requestStatusField;
            }
            set {
                this.requestStatusField = value;
            }
        }
        
        /// <remarks/>
        public int RequestedBy {
            get {
                return this.requestedByField;
            }
            set {
                this.requestedByField = value;
            }
        }
        
        /// <remarks/>
        public int UserId {
            get {
                return this.userIdField;
            }
            set {
                this.userIdField = value;
            }
        }
        
        /// <remarks/>
        public string District {
            get {
                return this.districtField;
            }
            set {
                this.districtField = value;
            }
        }
        
        /// <remarks/>
        public int IsLocked {
            get {
                return this.isLockedField;
            }
            set {
                this.isLockedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class VdcMun {
        
        private int districtField;
        
        private string vdcMunNameEngField;
        
        private string vdcMunNameNepField;
        
        private string vdcMunTypeField;
        
        private string vdcMunCodeField;
        
        private string vdcMunIdField;
        
        private int isEnableField;
        
        private int isLockedField;
        
        /// <remarks/>
        public int District {
            get {
                return this.districtField;
            }
            set {
                this.districtField = value;
            }
        }
        
        /// <remarks/>
        public string VdcMunNameEng {
            get {
                return this.vdcMunNameEngField;
            }
            set {
                this.vdcMunNameEngField = value;
            }
        }
        
        /// <remarks/>
        public string VdcMunNameNep {
            get {
                return this.vdcMunNameNepField;
            }
            set {
                this.vdcMunNameNepField = value;
            }
        }
        
        /// <remarks/>
        public string VdcMunType {
            get {
                return this.vdcMunTypeField;
            }
            set {
                this.vdcMunTypeField = value;
            }
        }
        
        /// <remarks/>
        public string VdcMunCode {
            get {
                return this.vdcMunCodeField;
            }
            set {
                this.vdcMunCodeField = value;
            }
        }
        
        /// <remarks/>
        public string VdcMunId {
            get {
                return this.vdcMunIdField;
            }
            set {
                this.vdcMunIdField = value;
            }
        }
        
        /// <remarks/>
        public int IsEnable {
            get {
                return this.isEnableField;
            }
            set {
                this.isEnableField = value;
            }
        }
        
        /// <remarks/>
        public int IsLocked {
            get {
                return this.isLockedField;
            }
            set {
                this.isLockedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void HelloWorldCompletedEventHandler(object sender, HelloWorldCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void InsertVdcMunCompletedEventHandler(object sender, InsertVdcMunCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InsertVdcMunCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InsertVdcMunCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void DeleteVdcMunByIdCompletedEventHandler(object sender, DeleteVdcMunByIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteVdcMunByIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteVdcMunByIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void SearchVdcMunByDistrictCompletedEventHandler(object sender, SearchVdcMunByDistrictCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SearchVdcMunByDistrictCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SearchVdcMunByDistrictCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void FetchMunVdcDetailsByIdCompletedEventHandler(object sender, FetchMunVdcDetailsByIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FetchMunVdcDetailsByIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FetchMunVdcDetailsByIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void UpdateVdcMunByIdCompletedEventHandler(object sender, UpdateVdcMunByIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateVdcMunByIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateVdcMunByIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void FetchAllVdcMunCompletedEventHandler(object sender, FetchAllVdcMunCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FetchAllVdcMunCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FetchAllVdcMunCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void populateVdcMunCompletedEventHandler(object sender, populateVdcMunCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class populateVdcMunCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal populateVdcMunCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void LockVdcMunCompletedEventHandler(object sender, LockVdcMunCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LockVdcMunCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LockVdcMunCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void UnlockVdcMunCompletedEventHandler(object sender, UnlockVdcMunCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UnlockVdcMunCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UnlockVdcMunCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591