//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace MISUI.ServiceActivityMgmt {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ActivityManagementServiceSoap", Namespace="http://tempuri.org/")]
    public partial class ActivityManagementService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private AuthSoapHd authSoapHdValueField;
        
        private System.Threading.SendOrPostCallback PopulateActivityOutputMapDetailOperationCompleted;
        
        private System.Threading.SendOrPostCallback PopulateActivityDetailOperationCompleted;
        
        private System.Threading.SendOrPostCallback SelectActivityDetailByIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback ActivityDetailOperationCompleted;
        
        private System.Threading.SendOrPostCallback SelectActivityUnitOperationCompleted;
        
        private System.Threading.SendOrPostCallback ActivityOutputMapOperationCompleted;
        
        private System.Threading.SendOrPostCallback SelectActivityOutputByIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback SelectActivityDetailBySectorOperationCompleted;
        
        private System.Threading.SendOrPostCallback SelectActivityOutputBySectorOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ActivityManagementService() {
            this.Url = global::MISUI.Properties.Settings.Default.MISUI_SeerviceActivityMgmt_ActivityManagementService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public AuthSoapHd AuthSoapHdValue {
            get {
                return this.authSoapHdValueField;
            }
            set {
                this.authSoapHdValueField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event PopulateActivityOutputMapDetailCompletedEventHandler PopulateActivityOutputMapDetailCompleted;
        
        /// <remarks/>
        public event PopulateActivityDetailCompletedEventHandler PopulateActivityDetailCompleted;
        
        /// <remarks/>
        public event SelectActivityDetailByIdCompletedEventHandler SelectActivityDetailByIdCompleted;
        
        /// <remarks/>
        public event ActivityDetailCompletedEventHandler ActivityDetailCompleted;
        
        /// <remarks/>
        public event SelectActivityUnitCompletedEventHandler SelectActivityUnitCompleted;
        
        /// <remarks/>
        public event ActivityOutputMapCompletedEventHandler ActivityOutputMapCompleted;
        
        /// <remarks/>
        public event SelectActivityOutputByIdCompletedEventHandler SelectActivityOutputByIdCompleted;
        
        /// <remarks/>
        public event SelectActivityDetailBySectorCompletedEventHandler SelectActivityDetailBySectorCompleted;
        
        /// <remarks/>
        public event SelectActivityOutputBySectorCompletedEventHandler SelectActivityOutputBySectorCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthSoapHdValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PopulateActivityOutputMapDetail", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable PopulateActivityOutputMapDetail(ActivityOutputMapBO objActivityOutputMap) {
            object[] results = this.Invoke("PopulateActivityOutputMapDetail", new object[] {
                        objActivityOutputMap});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void PopulateActivityOutputMapDetailAsync(ActivityOutputMapBO objActivityOutputMap) {
            this.PopulateActivityOutputMapDetailAsync(objActivityOutputMap, null);
        }
        
        /// <remarks/>
        public void PopulateActivityOutputMapDetailAsync(ActivityOutputMapBO objActivityOutputMap, object userState) {
            if ((this.PopulateActivityOutputMapDetailOperationCompleted == null)) {
                this.PopulateActivityOutputMapDetailOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPopulateActivityOutputMapDetailOperationCompleted);
            }
            this.InvokeAsync("PopulateActivityOutputMapDetail", new object[] {
                        objActivityOutputMap}, this.PopulateActivityOutputMapDetailOperationCompleted, userState);
        }
        
        private void OnPopulateActivityOutputMapDetailOperationCompleted(object arg) {
            if ((this.PopulateActivityOutputMapDetailCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PopulateActivityOutputMapDetailCompleted(this, new PopulateActivityOutputMapDetailCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthSoapHdValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PopulateActivityDetail", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable PopulateActivityDetail(ActivityDetailBO objActivityDetail) {
            object[] results = this.Invoke("PopulateActivityDetail", new object[] {
                        objActivityDetail});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void PopulateActivityDetailAsync(ActivityDetailBO objActivityDetail) {
            this.PopulateActivityDetailAsync(objActivityDetail, null);
        }
        
        /// <remarks/>
        public void PopulateActivityDetailAsync(ActivityDetailBO objActivityDetail, object userState) {
            if ((this.PopulateActivityDetailOperationCompleted == null)) {
                this.PopulateActivityDetailOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPopulateActivityDetailOperationCompleted);
            }
            this.InvokeAsync("PopulateActivityDetail", new object[] {
                        objActivityDetail}, this.PopulateActivityDetailOperationCompleted, userState);
        }
        
        private void OnPopulateActivityDetailOperationCompleted(object arg) {
            if ((this.PopulateActivityDetailCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PopulateActivityDetailCompleted(this, new PopulateActivityDetailCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthSoapHdValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SelectActivityDetailById", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable SelectActivityDetailById(ActivityDetailBO objActivityDetail) {
            object[] results = this.Invoke("SelectActivityDetailById", new object[] {
                        objActivityDetail});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void SelectActivityDetailByIdAsync(ActivityDetailBO objActivityDetail) {
            this.SelectActivityDetailByIdAsync(objActivityDetail, null);
        }
        
        /// <remarks/>
        public void SelectActivityDetailByIdAsync(ActivityDetailBO objActivityDetail, object userState) {
            if ((this.SelectActivityDetailByIdOperationCompleted == null)) {
                this.SelectActivityDetailByIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSelectActivityDetailByIdOperationCompleted);
            }
            this.InvokeAsync("SelectActivityDetailById", new object[] {
                        objActivityDetail}, this.SelectActivityDetailByIdOperationCompleted, userState);
        }
        
        private void OnSelectActivityDetailByIdOperationCompleted(object arg) {
            if ((this.SelectActivityDetailByIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SelectActivityDetailByIdCompleted(this, new SelectActivityDetailByIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthSoapHdValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ActivityDetail", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int ActivityDetail(ActivityDetailBO objActivityDetail) {
            object[] results = this.Invoke("ActivityDetail", new object[] {
                        objActivityDetail});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void ActivityDetailAsync(ActivityDetailBO objActivityDetail) {
            this.ActivityDetailAsync(objActivityDetail, null);
        }
        
        /// <remarks/>
        public void ActivityDetailAsync(ActivityDetailBO objActivityDetail, object userState) {
            if ((this.ActivityDetailOperationCompleted == null)) {
                this.ActivityDetailOperationCompleted = new System.Threading.SendOrPostCallback(this.OnActivityDetailOperationCompleted);
            }
            this.InvokeAsync("ActivityDetail", new object[] {
                        objActivityDetail}, this.ActivityDetailOperationCompleted, userState);
        }
        
        private void OnActivityDetailOperationCompleted(object arg) {
            if ((this.ActivityDetailCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ActivityDetailCompleted(this, new ActivityDetailCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthSoapHdValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SelectActivityUnit", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable SelectActivityUnit(ActivityDetailBO objActivityDetail) {
            object[] results = this.Invoke("SelectActivityUnit", new object[] {
                        objActivityDetail});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void SelectActivityUnitAsync(ActivityDetailBO objActivityDetail) {
            this.SelectActivityUnitAsync(objActivityDetail, null);
        }
        
        /// <remarks/>
        public void SelectActivityUnitAsync(ActivityDetailBO objActivityDetail, object userState) {
            if ((this.SelectActivityUnitOperationCompleted == null)) {
                this.SelectActivityUnitOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSelectActivityUnitOperationCompleted);
            }
            this.InvokeAsync("SelectActivityUnit", new object[] {
                        objActivityDetail}, this.SelectActivityUnitOperationCompleted, userState);
        }
        
        private void OnSelectActivityUnitOperationCompleted(object arg) {
            if ((this.SelectActivityUnitCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SelectActivityUnitCompleted(this, new SelectActivityUnitCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthSoapHdValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ActivityOutputMap", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int ActivityOutputMap(ActivityOutputMapBO objActivityMapBo) {
            object[] results = this.Invoke("ActivityOutputMap", new object[] {
                        objActivityMapBo});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void ActivityOutputMapAsync(ActivityOutputMapBO objActivityMapBo) {
            this.ActivityOutputMapAsync(objActivityMapBo, null);
        }
        
        /// <remarks/>
        public void ActivityOutputMapAsync(ActivityOutputMapBO objActivityMapBo, object userState) {
            if ((this.ActivityOutputMapOperationCompleted == null)) {
                this.ActivityOutputMapOperationCompleted = new System.Threading.SendOrPostCallback(this.OnActivityOutputMapOperationCompleted);
            }
            this.InvokeAsync("ActivityOutputMap", new object[] {
                        objActivityMapBo}, this.ActivityOutputMapOperationCompleted, userState);
        }
        
        private void OnActivityOutputMapOperationCompleted(object arg) {
            if ((this.ActivityOutputMapCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ActivityOutputMapCompleted(this, new ActivityOutputMapCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthSoapHdValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SelectActivityOutputById", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable SelectActivityOutputById(ActivityOutputMapBO objActivityDetail) {
            object[] results = this.Invoke("SelectActivityOutputById", new object[] {
                        objActivityDetail});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void SelectActivityOutputByIdAsync(ActivityOutputMapBO objActivityDetail) {
            this.SelectActivityOutputByIdAsync(objActivityDetail, null);
        }
        
        /// <remarks/>
        public void SelectActivityOutputByIdAsync(ActivityOutputMapBO objActivityDetail, object userState) {
            if ((this.SelectActivityOutputByIdOperationCompleted == null)) {
                this.SelectActivityOutputByIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSelectActivityOutputByIdOperationCompleted);
            }
            this.InvokeAsync("SelectActivityOutputById", new object[] {
                        objActivityDetail}, this.SelectActivityOutputByIdOperationCompleted, userState);
        }
        
        private void OnSelectActivityOutputByIdOperationCompleted(object arg) {
            if ((this.SelectActivityOutputByIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SelectActivityOutputByIdCompleted(this, new SelectActivityOutputByIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthSoapHdValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SelectActivityDetailBySector", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable SelectActivityDetailBySector(ActivityDetailBO objActivityDetail) {
            object[] results = this.Invoke("SelectActivityDetailBySector", new object[] {
                        objActivityDetail});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void SelectActivityDetailBySectorAsync(ActivityDetailBO objActivityDetail) {
            this.SelectActivityDetailBySectorAsync(objActivityDetail, null);
        }
        
        /// <remarks/>
        public void SelectActivityDetailBySectorAsync(ActivityDetailBO objActivityDetail, object userState) {
            if ((this.SelectActivityDetailBySectorOperationCompleted == null)) {
                this.SelectActivityDetailBySectorOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSelectActivityDetailBySectorOperationCompleted);
            }
            this.InvokeAsync("SelectActivityDetailBySector", new object[] {
                        objActivityDetail}, this.SelectActivityDetailBySectorOperationCompleted, userState);
        }
        
        private void OnSelectActivityDetailBySectorOperationCompleted(object arg) {
            if ((this.SelectActivityDetailBySectorCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SelectActivityDetailBySectorCompleted(this, new SelectActivityDetailBySectorCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthSoapHdValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SelectActivityOutputBySector", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable SelectActivityOutputBySector(ActivityDetailBO objActivityDetail) {
            object[] results = this.Invoke("SelectActivityOutputBySector", new object[] {
                        objActivityDetail});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void SelectActivityOutputBySectorAsync(ActivityDetailBO objActivityDetail) {
            this.SelectActivityOutputBySectorAsync(objActivityDetail, null);
        }
        
        /// <remarks/>
        public void SelectActivityOutputBySectorAsync(ActivityDetailBO objActivityDetail, object userState) {
            if ((this.SelectActivityOutputBySectorOperationCompleted == null)) {
                this.SelectActivityOutputBySectorOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSelectActivityOutputBySectorOperationCompleted);
            }
            this.InvokeAsync("SelectActivityOutputBySector", new object[] {
                        objActivityDetail}, this.SelectActivityOutputBySectorOperationCompleted, userState);
        }
        
        private void OnSelectActivityOutputBySectorOperationCompleted(object arg) {
            if ((this.SelectActivityOutputBySectorCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SelectActivityOutputBySectorCompleted(this, new SelectActivityOutputBySectorCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/", IsNullable=false)]
    public partial class AuthSoapHd : System.Web.Services.Protocols.SoapHeader {
        
        private string strUserNameField;
        
        private string strPasswordField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        public string strUserName {
            get {
                return this.strUserNameField;
            }
            set {
                this.strUserNameField = value;
            }
        }
        
        /// <remarks/>
        public string strPassword {
            get {
                return this.strPasswordField;
            }
            set {
                this.strPasswordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ActivityDetailBO {
        
        private decimal activityDetailIdField;
        
        private string activityDetailEngNameField;
        
        private string activityDetailNepNameField;
        
        private decimal activityUnitIdField;
        
        private decimal isenableField;
        
        private decimal islockedField;
        
        private decimal activitySubSectorIdField;
        
        private string langField;
        
        private string modeField;
        
        /// <remarks/>
        public decimal ActivityDetailId {
            get {
                return this.activityDetailIdField;
            }
            set {
                this.activityDetailIdField = value;
            }
        }
        
        /// <remarks/>
        public string ActivityDetailEngName {
            get {
                return this.activityDetailEngNameField;
            }
            set {
                this.activityDetailEngNameField = value;
            }
        }
        
        /// <remarks/>
        public string ActivityDetailNepName {
            get {
                return this.activityDetailNepNameField;
            }
            set {
                this.activityDetailNepNameField = value;
            }
        }
        
        /// <remarks/>
        public decimal ActivityUnitId {
            get {
                return this.activityUnitIdField;
            }
            set {
                this.activityUnitIdField = value;
            }
        }
        
        /// <remarks/>
        public decimal Isenable {
            get {
                return this.isenableField;
            }
            set {
                this.isenableField = value;
            }
        }
        
        /// <remarks/>
        public decimal Islocked {
            get {
                return this.islockedField;
            }
            set {
                this.islockedField = value;
            }
        }
        
        /// <remarks/>
        public decimal ActivitySubSectorId {
            get {
                return this.activitySubSectorIdField;
            }
            set {
                this.activitySubSectorIdField = value;
            }
        }
        
        /// <remarks/>
        public string Lang {
            get {
                return this.langField;
            }
            set {
                this.langField = value;
            }
        }
        
        /// <remarks/>
        public string Mode {
            get {
                return this.modeField;
            }
            set {
                this.modeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ActivityOutputMapBO {
        
        private decimal activityOutputMapIdField;
        
        private decimal activityDetailIdField;
        
        private decimal activityOutputIdField;
        
        private decimal fiscalYearIdField;
        
        private decimal isenabledField;
        
        private decimal islockedField;
        
        private string langField;
        
        private string modeField;
        
        /// <remarks/>
        public decimal ActivityOutputMapId {
            get {
                return this.activityOutputMapIdField;
            }
            set {
                this.activityOutputMapIdField = value;
            }
        }
        
        /// <remarks/>
        public decimal ActivityDetailId {
            get {
                return this.activityDetailIdField;
            }
            set {
                this.activityDetailIdField = value;
            }
        }
        
        /// <remarks/>
        public decimal ActivityOutputId {
            get {
                return this.activityOutputIdField;
            }
            set {
                this.activityOutputIdField = value;
            }
        }
        
        /// <remarks/>
        public decimal FiscalYearId {
            get {
                return this.fiscalYearIdField;
            }
            set {
                this.fiscalYearIdField = value;
            }
        }
        
        /// <remarks/>
        public decimal Isenabled {
            get {
                return this.isenabledField;
            }
            set {
                this.isenabledField = value;
            }
        }
        
        /// <remarks/>
        public decimal Islocked {
            get {
                return this.islockedField;
            }
            set {
                this.islockedField = value;
            }
        }
        
        /// <remarks/>
        public string Lang {
            get {
                return this.langField;
            }
            set {
                this.langField = value;
            }
        }
        
        /// <remarks/>
        public string Mode {
            get {
                return this.modeField;
            }
            set {
                this.modeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void PopulateActivityOutputMapDetailCompletedEventHandler(object sender, PopulateActivityOutputMapDetailCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PopulateActivityOutputMapDetailCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PopulateActivityOutputMapDetailCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void PopulateActivityDetailCompletedEventHandler(object sender, PopulateActivityDetailCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PopulateActivityDetailCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PopulateActivityDetailCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void SelectActivityDetailByIdCompletedEventHandler(object sender, SelectActivityDetailByIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SelectActivityDetailByIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SelectActivityDetailByIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void ActivityDetailCompletedEventHandler(object sender, ActivityDetailCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ActivityDetailCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ActivityDetailCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void SelectActivityUnitCompletedEventHandler(object sender, SelectActivityUnitCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SelectActivityUnitCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SelectActivityUnitCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void ActivityOutputMapCompletedEventHandler(object sender, ActivityOutputMapCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ActivityOutputMapCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ActivityOutputMapCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void SelectActivityOutputByIdCompletedEventHandler(object sender, SelectActivityOutputByIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SelectActivityOutputByIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SelectActivityOutputByIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void SelectActivityDetailBySectorCompletedEventHandler(object sender, SelectActivityDetailBySectorCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SelectActivityDetailBySectorCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SelectActivityDetailBySectorCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void SelectActivityOutputBySectorCompletedEventHandler(object sender, SelectActivityOutputBySectorCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SelectActivityOutputBySectorCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SelectActivityOutputBySectorCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591