//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace MISUI.ServiceOutputTarget {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="OutputTargetServiceSoap", Namespace="http://tempuri.org/")]
    public partial class OutputTargetService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private AuthSoapHd authSoapHdValueField;
        
        private System.Threading.SendOrPostCallback SelectTargetOperationCompleted;
        
        private System.Threading.SendOrPostCallback PopulateAllTargetsOperationCompleted;
        
        private System.Threading.SendOrPostCallback PopulateProjectTargetsOperationCompleted;
        
        private System.Threading.SendOrPostCallback PopulateTargetByIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddTargetOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddProjectOutputTargetOperationCompleted;
        
        private System.Threading.SendOrPostCallback SelectFrameworkOperationCompleted;
        
        private System.Threading.SendOrPostCallback SelectOutputOperationCompleted;
        
        private System.Threading.SendOrPostCallback populateOutputTypeOperationCompleted;
        
        private System.Threading.SendOrPostCallback PopulateAllOutputsOperationCompleted;
        
        private System.Threading.SendOrPostCallback PopulateOutputByIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddOutputOperationCompleted;
        
        private System.Threading.SendOrPostCallback populateSubSectorOperationCompleted;
        
        private System.Threading.SendOrPostCallback PopulateSectorsToFilterOperationCompleted;
        
        private System.Threading.SendOrPostCallback PopulateSubSectorsToFilterOperationCompleted;
        
        private System.Threading.SendOrPostCallback PopulateAllActivitiesToFilterOperationCompleted;
        
        private System.Threading.SendOrPostCallback PopulateOfficeOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public OutputTargetService() {
            this.Url = global::MISUI.Properties.Settings.Default.MISUI_ServiceOutputTarget_OutputTargetService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public AuthSoapHd AuthSoapHdValue {
            get {
                return this.authSoapHdValueField;
            }
            set {
                this.authSoapHdValueField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SelectTargetCompletedEventHandler SelectTargetCompleted;
        
        /// <remarks/>
        public event PopulateAllTargetsCompletedEventHandler PopulateAllTargetsCompleted;
        
        /// <remarks/>
        public event PopulateProjectTargetsCompletedEventHandler PopulateProjectTargetsCompleted;
        
        /// <remarks/>
        public event PopulateTargetByIdCompletedEventHandler PopulateTargetByIdCompleted;
        
        /// <remarks/>
        public event AddTargetCompletedEventHandler AddTargetCompleted;
        
        /// <remarks/>
        public event AddProjectOutputTargetCompletedEventHandler AddProjectOutputTargetCompleted;
        
        /// <remarks/>
        public event SelectFrameworkCompletedEventHandler SelectFrameworkCompleted;
        
        /// <remarks/>
        public event SelectOutputCompletedEventHandler SelectOutputCompleted;
        
        /// <remarks/>
        public event populateOutputTypeCompletedEventHandler populateOutputTypeCompleted;
        
        /// <remarks/>
        public event PopulateAllOutputsCompletedEventHandler PopulateAllOutputsCompleted;
        
        /// <remarks/>
        public event PopulateOutputByIdCompletedEventHandler PopulateOutputByIdCompleted;
        
        /// <remarks/>
        public event AddOutputCompletedEventHandler AddOutputCompleted;
        
        /// <remarks/>
        public event populateSubSectorCompletedEventHandler populateSubSectorCompleted;
        
        /// <remarks/>
        public event PopulateSectorsToFilterCompletedEventHandler PopulateSectorsToFilterCompleted;
        
        /// <remarks/>
        public event PopulateSubSectorsToFilterCompletedEventHandler PopulateSubSectorsToFilterCompleted;
        
        /// <remarks/>
        public event PopulateAllActivitiesToFilterCompletedEventHandler PopulateAllActivitiesToFilterCompleted;
        
        /// <remarks/>
        public event PopulateOfficeCompletedEventHandler PopulateOfficeCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthSoapHdValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SelectTarget", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable SelectTarget(OutputTarget objOutputTarget) {
            object[] results = this.Invoke("SelectTarget", new object[] {
                        objOutputTarget});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void SelectTargetAsync(OutputTarget objOutputTarget) {
            this.SelectTargetAsync(objOutputTarget, null);
        }
        
        /// <remarks/>
        public void SelectTargetAsync(OutputTarget objOutputTarget, object userState) {
            if ((this.SelectTargetOperationCompleted == null)) {
                this.SelectTargetOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSelectTargetOperationCompleted);
            }
            this.InvokeAsync("SelectTarget", new object[] {
                        objOutputTarget}, this.SelectTargetOperationCompleted, userState);
        }
        
        private void OnSelectTargetOperationCompleted(object arg) {
            if ((this.SelectTargetCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SelectTargetCompleted(this, new SelectTargetCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthSoapHdValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PopulateAllTargets", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable PopulateAllTargets(OutputTarget objOutputTarget) {
            object[] results = this.Invoke("PopulateAllTargets", new object[] {
                        objOutputTarget});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void PopulateAllTargetsAsync(OutputTarget objOutputTarget) {
            this.PopulateAllTargetsAsync(objOutputTarget, null);
        }
        
        /// <remarks/>
        public void PopulateAllTargetsAsync(OutputTarget objOutputTarget, object userState) {
            if ((this.PopulateAllTargetsOperationCompleted == null)) {
                this.PopulateAllTargetsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPopulateAllTargetsOperationCompleted);
            }
            this.InvokeAsync("PopulateAllTargets", new object[] {
                        objOutputTarget}, this.PopulateAllTargetsOperationCompleted, userState);
        }
        
        private void OnPopulateAllTargetsOperationCompleted(object arg) {
            if ((this.PopulateAllTargetsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PopulateAllTargetsCompleted(this, new PopulateAllTargetsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthSoapHdValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PopulateProjectTargets", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable PopulateProjectTargets(OutputTarget objOutputTarget) {
            object[] results = this.Invoke("PopulateProjectTargets", new object[] {
                        objOutputTarget});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void PopulateProjectTargetsAsync(OutputTarget objOutputTarget) {
            this.PopulateProjectTargetsAsync(objOutputTarget, null);
        }
        
        /// <remarks/>
        public void PopulateProjectTargetsAsync(OutputTarget objOutputTarget, object userState) {
            if ((this.PopulateProjectTargetsOperationCompleted == null)) {
                this.PopulateProjectTargetsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPopulateProjectTargetsOperationCompleted);
            }
            this.InvokeAsync("PopulateProjectTargets", new object[] {
                        objOutputTarget}, this.PopulateProjectTargetsOperationCompleted, userState);
        }
        
        private void OnPopulateProjectTargetsOperationCompleted(object arg) {
            if ((this.PopulateProjectTargetsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PopulateProjectTargetsCompleted(this, new PopulateProjectTargetsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthSoapHdValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PopulateTargetById", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable PopulateTargetById(OutputTarget objOutputTarget) {
            object[] results = this.Invoke("PopulateTargetById", new object[] {
                        objOutputTarget});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void PopulateTargetByIdAsync(OutputTarget objOutputTarget) {
            this.PopulateTargetByIdAsync(objOutputTarget, null);
        }
        
        /// <remarks/>
        public void PopulateTargetByIdAsync(OutputTarget objOutputTarget, object userState) {
            if ((this.PopulateTargetByIdOperationCompleted == null)) {
                this.PopulateTargetByIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPopulateTargetByIdOperationCompleted);
            }
            this.InvokeAsync("PopulateTargetById", new object[] {
                        objOutputTarget}, this.PopulateTargetByIdOperationCompleted, userState);
        }
        
        private void OnPopulateTargetByIdOperationCompleted(object arg) {
            if ((this.PopulateTargetByIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PopulateTargetByIdCompleted(this, new PopulateTargetByIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthSoapHdValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AddTarget", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int AddTarget(OutputTarget objOutputTarget) {
            object[] results = this.Invoke("AddTarget", new object[] {
                        objOutputTarget});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void AddTargetAsync(OutputTarget objOutputTarget) {
            this.AddTargetAsync(objOutputTarget, null);
        }
        
        /// <remarks/>
        public void AddTargetAsync(OutputTarget objOutputTarget, object userState) {
            if ((this.AddTargetOperationCompleted == null)) {
                this.AddTargetOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddTargetOperationCompleted);
            }
            this.InvokeAsync("AddTarget", new object[] {
                        objOutputTarget}, this.AddTargetOperationCompleted, userState);
        }
        
        private void OnAddTargetOperationCompleted(object arg) {
            if ((this.AddTargetCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddTargetCompleted(this, new AddTargetCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthSoapHdValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AddProjectOutputTarget", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int AddProjectOutputTarget(OutputTarget objOutputTarget) {
            object[] results = this.Invoke("AddProjectOutputTarget", new object[] {
                        objOutputTarget});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void AddProjectOutputTargetAsync(OutputTarget objOutputTarget) {
            this.AddProjectOutputTargetAsync(objOutputTarget, null);
        }
        
        /// <remarks/>
        public void AddProjectOutputTargetAsync(OutputTarget objOutputTarget, object userState) {
            if ((this.AddProjectOutputTargetOperationCompleted == null)) {
                this.AddProjectOutputTargetOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddProjectOutputTargetOperationCompleted);
            }
            this.InvokeAsync("AddProjectOutputTarget", new object[] {
                        objOutputTarget}, this.AddProjectOutputTargetOperationCompleted, userState);
        }
        
        private void OnAddProjectOutputTargetOperationCompleted(object arg) {
            if ((this.AddProjectOutputTargetCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddProjectOutputTargetCompleted(this, new AddProjectOutputTargetCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthSoapHdValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SelectFramework", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable SelectFramework() {
            object[] results = this.Invoke("SelectFramework", new object[0]);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void SelectFrameworkAsync() {
            this.SelectFrameworkAsync(null);
        }
        
        /// <remarks/>
        public void SelectFrameworkAsync(object userState) {
            if ((this.SelectFrameworkOperationCompleted == null)) {
                this.SelectFrameworkOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSelectFrameworkOperationCompleted);
            }
            this.InvokeAsync("SelectFramework", new object[0], this.SelectFrameworkOperationCompleted, userState);
        }
        
        private void OnSelectFrameworkOperationCompleted(object arg) {
            if ((this.SelectFrameworkCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SelectFrameworkCompleted(this, new SelectFrameworkCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthSoapHdValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SelectOutput", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable SelectOutput(OutputTarget objOutputTarget) {
            object[] results = this.Invoke("SelectOutput", new object[] {
                        objOutputTarget});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void SelectOutputAsync(OutputTarget objOutputTarget) {
            this.SelectOutputAsync(objOutputTarget, null);
        }
        
        /// <remarks/>
        public void SelectOutputAsync(OutputTarget objOutputTarget, object userState) {
            if ((this.SelectOutputOperationCompleted == null)) {
                this.SelectOutputOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSelectOutputOperationCompleted);
            }
            this.InvokeAsync("SelectOutput", new object[] {
                        objOutputTarget}, this.SelectOutputOperationCompleted, userState);
        }
        
        private void OnSelectOutputOperationCompleted(object arg) {
            if ((this.SelectOutputCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SelectOutputCompleted(this, new SelectOutputCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthSoapHdValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/populateOutputType", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable populateOutputType(OutputTarget objOutputTarget) {
            object[] results = this.Invoke("populateOutputType", new object[] {
                        objOutputTarget});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void populateOutputTypeAsync(OutputTarget objOutputTarget) {
            this.populateOutputTypeAsync(objOutputTarget, null);
        }
        
        /// <remarks/>
        public void populateOutputTypeAsync(OutputTarget objOutputTarget, object userState) {
            if ((this.populateOutputTypeOperationCompleted == null)) {
                this.populateOutputTypeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnpopulateOutputTypeOperationCompleted);
            }
            this.InvokeAsync("populateOutputType", new object[] {
                        objOutputTarget}, this.populateOutputTypeOperationCompleted, userState);
        }
        
        private void OnpopulateOutputTypeOperationCompleted(object arg) {
            if ((this.populateOutputTypeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.populateOutputTypeCompleted(this, new populateOutputTypeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthSoapHdValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PopulateAllOutputs", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable PopulateAllOutputs(OutputTarget objOutputTarget) {
            object[] results = this.Invoke("PopulateAllOutputs", new object[] {
                        objOutputTarget});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void PopulateAllOutputsAsync(OutputTarget objOutputTarget) {
            this.PopulateAllOutputsAsync(objOutputTarget, null);
        }
        
        /// <remarks/>
        public void PopulateAllOutputsAsync(OutputTarget objOutputTarget, object userState) {
            if ((this.PopulateAllOutputsOperationCompleted == null)) {
                this.PopulateAllOutputsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPopulateAllOutputsOperationCompleted);
            }
            this.InvokeAsync("PopulateAllOutputs", new object[] {
                        objOutputTarget}, this.PopulateAllOutputsOperationCompleted, userState);
        }
        
        private void OnPopulateAllOutputsOperationCompleted(object arg) {
            if ((this.PopulateAllOutputsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PopulateAllOutputsCompleted(this, new PopulateAllOutputsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthSoapHdValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PopulateOutputById", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable PopulateOutputById(OutputTarget objOutputTarget) {
            object[] results = this.Invoke("PopulateOutputById", new object[] {
                        objOutputTarget});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void PopulateOutputByIdAsync(OutputTarget objOutputTarget) {
            this.PopulateOutputByIdAsync(objOutputTarget, null);
        }
        
        /// <remarks/>
        public void PopulateOutputByIdAsync(OutputTarget objOutputTarget, object userState) {
            if ((this.PopulateOutputByIdOperationCompleted == null)) {
                this.PopulateOutputByIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPopulateOutputByIdOperationCompleted);
            }
            this.InvokeAsync("PopulateOutputById", new object[] {
                        objOutputTarget}, this.PopulateOutputByIdOperationCompleted, userState);
        }
        
        private void OnPopulateOutputByIdOperationCompleted(object arg) {
            if ((this.PopulateOutputByIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PopulateOutputByIdCompleted(this, new PopulateOutputByIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthSoapHdValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AddOutput", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int AddOutput(OutputTarget objOutputTarget) {
            object[] results = this.Invoke("AddOutput", new object[] {
                        objOutputTarget});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void AddOutputAsync(OutputTarget objOutputTarget) {
            this.AddOutputAsync(objOutputTarget, null);
        }
        
        /// <remarks/>
        public void AddOutputAsync(OutputTarget objOutputTarget, object userState) {
            if ((this.AddOutputOperationCompleted == null)) {
                this.AddOutputOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddOutputOperationCompleted);
            }
            this.InvokeAsync("AddOutput", new object[] {
                        objOutputTarget}, this.AddOutputOperationCompleted, userState);
        }
        
        private void OnAddOutputOperationCompleted(object arg) {
            if ((this.AddOutputCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddOutputCompleted(this, new AddOutputCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthSoapHdValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/populateSubSector", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable populateSubSector(OutputTarget objOutputTarget) {
            object[] results = this.Invoke("populateSubSector", new object[] {
                        objOutputTarget});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void populateSubSectorAsync(OutputTarget objOutputTarget) {
            this.populateSubSectorAsync(objOutputTarget, null);
        }
        
        /// <remarks/>
        public void populateSubSectorAsync(OutputTarget objOutputTarget, object userState) {
            if ((this.populateSubSectorOperationCompleted == null)) {
                this.populateSubSectorOperationCompleted = new System.Threading.SendOrPostCallback(this.OnpopulateSubSectorOperationCompleted);
            }
            this.InvokeAsync("populateSubSector", new object[] {
                        objOutputTarget}, this.populateSubSectorOperationCompleted, userState);
        }
        
        private void OnpopulateSubSectorOperationCompleted(object arg) {
            if ((this.populateSubSectorCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.populateSubSectorCompleted(this, new populateSubSectorCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthSoapHdValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PopulateSectorsToFilter", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable PopulateSectorsToFilter(OutputTarget objOutputTarget) {
            object[] results = this.Invoke("PopulateSectorsToFilter", new object[] {
                        objOutputTarget});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void PopulateSectorsToFilterAsync(OutputTarget objOutputTarget) {
            this.PopulateSectorsToFilterAsync(objOutputTarget, null);
        }
        
        /// <remarks/>
        public void PopulateSectorsToFilterAsync(OutputTarget objOutputTarget, object userState) {
            if ((this.PopulateSectorsToFilterOperationCompleted == null)) {
                this.PopulateSectorsToFilterOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPopulateSectorsToFilterOperationCompleted);
            }
            this.InvokeAsync("PopulateSectorsToFilter", new object[] {
                        objOutputTarget}, this.PopulateSectorsToFilterOperationCompleted, userState);
        }
        
        private void OnPopulateSectorsToFilterOperationCompleted(object arg) {
            if ((this.PopulateSectorsToFilterCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PopulateSectorsToFilterCompleted(this, new PopulateSectorsToFilterCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthSoapHdValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PopulateSubSectorsToFilter", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable PopulateSubSectorsToFilter(OutputTarget objOutputTarget) {
            object[] results = this.Invoke("PopulateSubSectorsToFilter", new object[] {
                        objOutputTarget});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void PopulateSubSectorsToFilterAsync(OutputTarget objOutputTarget) {
            this.PopulateSubSectorsToFilterAsync(objOutputTarget, null);
        }
        
        /// <remarks/>
        public void PopulateSubSectorsToFilterAsync(OutputTarget objOutputTarget, object userState) {
            if ((this.PopulateSubSectorsToFilterOperationCompleted == null)) {
                this.PopulateSubSectorsToFilterOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPopulateSubSectorsToFilterOperationCompleted);
            }
            this.InvokeAsync("PopulateSubSectorsToFilter", new object[] {
                        objOutputTarget}, this.PopulateSubSectorsToFilterOperationCompleted, userState);
        }
        
        private void OnPopulateSubSectorsToFilterOperationCompleted(object arg) {
            if ((this.PopulateSubSectorsToFilterCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PopulateSubSectorsToFilterCompleted(this, new PopulateSubSectorsToFilterCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthSoapHdValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PopulateAllActivitiesToFilter", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable PopulateAllActivitiesToFilter(OutputTarget objOutputTarget) {
            object[] results = this.Invoke("PopulateAllActivitiesToFilter", new object[] {
                        objOutputTarget});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void PopulateAllActivitiesToFilterAsync(OutputTarget objOutputTarget) {
            this.PopulateAllActivitiesToFilterAsync(objOutputTarget, null);
        }
        
        /// <remarks/>
        public void PopulateAllActivitiesToFilterAsync(OutputTarget objOutputTarget, object userState) {
            if ((this.PopulateAllActivitiesToFilterOperationCompleted == null)) {
                this.PopulateAllActivitiesToFilterOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPopulateAllActivitiesToFilterOperationCompleted);
            }
            this.InvokeAsync("PopulateAllActivitiesToFilter", new object[] {
                        objOutputTarget}, this.PopulateAllActivitiesToFilterOperationCompleted, userState);
        }
        
        private void OnPopulateAllActivitiesToFilterOperationCompleted(object arg) {
            if ((this.PopulateAllActivitiesToFilterCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PopulateAllActivitiesToFilterCompleted(this, new PopulateAllActivitiesToFilterCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthSoapHdValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PopulateOffice", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable PopulateOffice(OutputTarget objOutputTarget) {
            object[] results = this.Invoke("PopulateOffice", new object[] {
                        objOutputTarget});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void PopulateOfficeAsync(OutputTarget objOutputTarget) {
            this.PopulateOfficeAsync(objOutputTarget, null);
        }
        
        /// <remarks/>
        public void PopulateOfficeAsync(OutputTarget objOutputTarget, object userState) {
            if ((this.PopulateOfficeOperationCompleted == null)) {
                this.PopulateOfficeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPopulateOfficeOperationCompleted);
            }
            this.InvokeAsync("PopulateOffice", new object[] {
                        objOutputTarget}, this.PopulateOfficeOperationCompleted, userState);
        }
        
        private void OnPopulateOfficeOperationCompleted(object arg) {
            if ((this.PopulateOfficeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PopulateOfficeCompleted(this, new PopulateOfficeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/", IsNullable=false)]
    public partial class AuthSoapHd : System.Web.Services.Protocols.SoapHeader {
        
        private string strUserNameField;
        
        private string strPasswordField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        public string strUserName {
            get {
                return this.strUserNameField;
            }
            set {
                this.strUserNameField = value;
            }
        }
        
        /// <remarks/>
        public string strPassword {
            get {
                return this.strPasswordField;
            }
            set {
                this.strPasswordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class OutputTarget {
        
        private decimal activityOutputIdField;
        
        private string activityOutputEngNameField;
        
        private string activityOutputNepNameField;
        
        private string activityOutputCodeField;
        
        private decimal activityOutputTypeIdField;
        
        private string toipYearField;
        
        private decimal subSectorIdField;
        
        private string modeField;
        
        private decimal isEnableField;
        
        private decimal isLockedField;
        
        private string langField;
        
        private decimal targetIdField;
        
        private string targetFirstYearField;
        
        private string targetSecondYearField;
        
        private string targetThirdYearField;
        
        private decimal activityOutputMapIdField;
        
        private decimal fiscalYearIdField;
        
        private decimal sectorIdField;
        
        private string overallTargetField;
        
        private string baseYearTargetField;
        
        private decimal projectIdField;
        
        private decimal frameworkIdField;
        
        private decimal ptargetIdField;
        
        private string pustyayiyekoShrotField;
        
        private string responsibleOfficeIdField;
        
        private int ministryIdField;
        
        private int parentOutputIdField;
        
        /// <remarks/>
        public decimal ActivityOutputId {
            get {
                return this.activityOutputIdField;
            }
            set {
                this.activityOutputIdField = value;
            }
        }
        
        /// <remarks/>
        public string ActivityOutputEngName {
            get {
                return this.activityOutputEngNameField;
            }
            set {
                this.activityOutputEngNameField = value;
            }
        }
        
        /// <remarks/>
        public string ActivityOutputNepName {
            get {
                return this.activityOutputNepNameField;
            }
            set {
                this.activityOutputNepNameField = value;
            }
        }
        
        /// <remarks/>
        public string ActivityOutputCode {
            get {
                return this.activityOutputCodeField;
            }
            set {
                this.activityOutputCodeField = value;
            }
        }
        
        /// <remarks/>
        public decimal ActivityOutputTypeId {
            get {
                return this.activityOutputTypeIdField;
            }
            set {
                this.activityOutputTypeIdField = value;
            }
        }
        
        /// <remarks/>
        public string ToipYear {
            get {
                return this.toipYearField;
            }
            set {
                this.toipYearField = value;
            }
        }
        
        /// <remarks/>
        public decimal SubSectorId {
            get {
                return this.subSectorIdField;
            }
            set {
                this.subSectorIdField = value;
            }
        }
        
        /// <remarks/>
        public string Mode {
            get {
                return this.modeField;
            }
            set {
                this.modeField = value;
            }
        }
        
        /// <remarks/>
        public decimal IsEnable {
            get {
                return this.isEnableField;
            }
            set {
                this.isEnableField = value;
            }
        }
        
        /// <remarks/>
        public decimal IsLocked {
            get {
                return this.isLockedField;
            }
            set {
                this.isLockedField = value;
            }
        }
        
        /// <remarks/>
        public string Lang {
            get {
                return this.langField;
            }
            set {
                this.langField = value;
            }
        }
        
        /// <remarks/>
        public decimal TargetId {
            get {
                return this.targetIdField;
            }
            set {
                this.targetIdField = value;
            }
        }
        
        /// <remarks/>
        public string TargetFirstYear {
            get {
                return this.targetFirstYearField;
            }
            set {
                this.targetFirstYearField = value;
            }
        }
        
        /// <remarks/>
        public string TargetSecondYear {
            get {
                return this.targetSecondYearField;
            }
            set {
                this.targetSecondYearField = value;
            }
        }
        
        /// <remarks/>
        public string TargetThirdYear {
            get {
                return this.targetThirdYearField;
            }
            set {
                this.targetThirdYearField = value;
            }
        }
        
        /// <remarks/>
        public decimal ActivityOutputMapId {
            get {
                return this.activityOutputMapIdField;
            }
            set {
                this.activityOutputMapIdField = value;
            }
        }
        
        /// <remarks/>
        public decimal FiscalYearId {
            get {
                return this.fiscalYearIdField;
            }
            set {
                this.fiscalYearIdField = value;
            }
        }
        
        /// <remarks/>
        public decimal SectorId {
            get {
                return this.sectorIdField;
            }
            set {
                this.sectorIdField = value;
            }
        }
        
        /// <remarks/>
        public string OverallTarget {
            get {
                return this.overallTargetField;
            }
            set {
                this.overallTargetField = value;
            }
        }
        
        /// <remarks/>
        public string BaseYearTarget {
            get {
                return this.baseYearTargetField;
            }
            set {
                this.baseYearTargetField = value;
            }
        }
        
        /// <remarks/>
        public decimal ProjectId {
            get {
                return this.projectIdField;
            }
            set {
                this.projectIdField = value;
            }
        }
        
        /// <remarks/>
        public decimal FrameworkId {
            get {
                return this.frameworkIdField;
            }
            set {
                this.frameworkIdField = value;
            }
        }
        
        /// <remarks/>
        public decimal PtargetId {
            get {
                return this.ptargetIdField;
            }
            set {
                this.ptargetIdField = value;
            }
        }
        
        /// <remarks/>
        public string PustyayiyekoShrot {
            get {
                return this.pustyayiyekoShrotField;
            }
            set {
                this.pustyayiyekoShrotField = value;
            }
        }
        
        /// <remarks/>
        public string ResponsibleOfficeId {
            get {
                return this.responsibleOfficeIdField;
            }
            set {
                this.responsibleOfficeIdField = value;
            }
        }
        
        /// <remarks/>
        public int MinistryId {
            get {
                return this.ministryIdField;
            }
            set {
                this.ministryIdField = value;
            }
        }
        
        /// <remarks/>
        public int ParentOutputId {
            get {
                return this.parentOutputIdField;
            }
            set {
                this.parentOutputIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void SelectTargetCompletedEventHandler(object sender, SelectTargetCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SelectTargetCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SelectTargetCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void PopulateAllTargetsCompletedEventHandler(object sender, PopulateAllTargetsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PopulateAllTargetsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PopulateAllTargetsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void PopulateProjectTargetsCompletedEventHandler(object sender, PopulateProjectTargetsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PopulateProjectTargetsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PopulateProjectTargetsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void PopulateTargetByIdCompletedEventHandler(object sender, PopulateTargetByIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PopulateTargetByIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PopulateTargetByIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void AddTargetCompletedEventHandler(object sender, AddTargetCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddTargetCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddTargetCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void AddProjectOutputTargetCompletedEventHandler(object sender, AddProjectOutputTargetCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddProjectOutputTargetCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddProjectOutputTargetCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void SelectFrameworkCompletedEventHandler(object sender, SelectFrameworkCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SelectFrameworkCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SelectFrameworkCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void SelectOutputCompletedEventHandler(object sender, SelectOutputCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SelectOutputCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SelectOutputCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void populateOutputTypeCompletedEventHandler(object sender, populateOutputTypeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class populateOutputTypeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal populateOutputTypeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void PopulateAllOutputsCompletedEventHandler(object sender, PopulateAllOutputsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PopulateAllOutputsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PopulateAllOutputsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void PopulateOutputByIdCompletedEventHandler(object sender, PopulateOutputByIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PopulateOutputByIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PopulateOutputByIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void AddOutputCompletedEventHandler(object sender, AddOutputCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddOutputCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddOutputCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void populateSubSectorCompletedEventHandler(object sender, populateSubSectorCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class populateSubSectorCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal populateSubSectorCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void PopulateSectorsToFilterCompletedEventHandler(object sender, PopulateSectorsToFilterCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PopulateSectorsToFilterCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PopulateSectorsToFilterCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void PopulateSubSectorsToFilterCompletedEventHandler(object sender, PopulateSubSectorsToFilterCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PopulateSubSectorsToFilterCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PopulateSubSectorsToFilterCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void PopulateAllActivitiesToFilterCompletedEventHandler(object sender, PopulateAllActivitiesToFilterCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PopulateAllActivitiesToFilterCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PopulateAllActivitiesToFilterCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void PopulateOfficeCompletedEventHandler(object sender, PopulateOfficeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PopulateOfficeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PopulateOfficeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591